#
# LXC
#

com.liferay.lxc.dxp.domains=\
  www-dev.liferay.com,\
  www.liferay.com
com.liferay.lxc.dxp.mainDomain=www-dev.liferay.com
com.liferay.lxc.dxp.server.protocol=https

#
# OAuth
#

a7855d10-6a20-1f0e-7e21-53d8654a09d2.oauth2.headless.server.client.secret=secret-5ca967ea-5fe5-8953-3a44-7b52cac788b1
9fc0c45b-d42f-1fcd-09c3-a4b8e6ec4268.oauth2.headless.server.client.secret=secret-10a5e713-2426-7bda-04bd-930f44247ca
liferay.oauth.application.external.reference.codes=\
    a7855d10-6a20-1f0e-7e21-53d8654a09d2,\
    9fc0c45b-d42f-1fcd-09c3-a4b8e6ec4268