#
# Application
#

liferay.learn.google.rag.credentials=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=

liferay.oauth.urls.excludes=\
    /rag/document,\
    /rag/search,\
    /ready

#
# Spring Boot
#

server.port=58081

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.collection-name=learn

spring.ai.vertex.ai.embedding.text.options.model=gemini-embedding-001
spring.ai.vertex.ai.embedding.text.options.task-type=RETRIEVAL_DOCUMENT
spring.ai.vertex.ai.embedding.project-id=devcon25-476012
spring.ai.vertex.ai.embedding.location=us-central1

spring.ai.vertex.ai.gemini.project-id=devcon25-476012
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash
spring.ai.vertex.ai.gemini.credentials-uri=file:/opt/liferay/resources.json