#
# Application
#

liferay.ai.hub.crawler.elasticsearch.host=
liferay.ai.hub.crawler.elasticsearch.pipeline=
liferay.ai.hub.crawler.elasticsearch.port=
liferay.ai.hub.crawler.executor=local-process
liferay.ai.hub.crawler.gcp.job.name=
liferay.ai.hub.crawler.gcp.project=
liferay.ai.hub.crawler.gcp.region=
liferay.ai.hub.crawler.headless.client.id=
liferay.ai.hub.crawler.headless.client.secret=
liferay.ai.hub.crawler.headless.crawljobs.path=/o/c/crawljobs
liferay.ai.hub.crawler.headless.url=http://localhost:8080
liferay.ai.hub.crawler.k8s.image=
liferay.ai.hub.crawler.k8s.namespace=
liferay.ai.hub.crawler.log.level=info
liferay.ai.hub.crawler.max.crawl.depth=1
liferay.ai.hub.crawler.max.duration=30
liferay.ai.hub.crawler.reaper.cron=0 */5 * * * *
liferay.ai.hub.crawler.reaper.stale.minutes=15
liferay.ai.hub.crawler.smoke.endpoint.enabled=false
liferay.ai.hub.crawler.url.queue.size.limit=50000

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-aihub-etc-spring-boot-oaua
liferay.oauth.urls.excludes=/error,/ready,/smoke/dispatch

#
# Spring Boot
#

server.port=58081